version: '3.6'
services:
  postgres:
    image: bitnine/agensgraph:v2.1.1
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 5432:5432
    # volumes:
    #   - "./data/postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    command: ["bin/bash"]
    tty: true
    stdin_open: true

  webapp:
    build: .
    image: metadata_center:dev
    ports:
      - "5000:5000"
    command: "python metadata_center run"